<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="TestAll" duration-ms="30" started-at="2014-03-16T07:49:14Z" finished-at="2014-03-16T07:49:14Z">
    <groups>
    </groups>
    <test name="case1" duration-ms="30" started-at="2014-03-16T07:49:14Z" finished-at="2014-03-16T07:49:14Z">
      <class name="com.ddlab.rnd.testng.test.AppTest1">
        <test-method status="PASS" signature="testLinuxOnly()[pri:0, instance:com.ddlab.rnd.testng.test.AppTest1@299bc338]" name="testLinuxOnly" duration-ms="5" started-at="2014-03-16T13:19:14Z" finished-at="2014-03-16T13:19:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLinuxOnly -->
      </class> <!-- com.ddlab.rnd.testng.test.AppTest1 -->
      <class name="com.ddlab.rnd.testng.test.DummyTest">
        <test-method status="PASS" signature="init()[pri:0, instance:com.ddlab.rnd.testng.test.DummyTest@7b811ce0]" name="init" is-config="true" duration-ms="8" started-at="2014-03-16T13:19:14Z" finished-at="2014-03-16T13:19:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="test1()[pri:0, instance:com.ddlab.rnd.testng.test.DummyTest@7b811ce0]" name="test1" duration-ms="1" started-at="2014-03-16T13:19:14Z" finished-at="2014-03-16T13:19:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method status="FAIL" signature="test2()[pri:0, instance:com.ddlab.rnd.testng.test.DummyTest@7b811ce0]" name="test2" duration-ms="0" started-at="2014-03-16T13:19:14Z" finished-at="2014-03-16T13:19:14Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at com.ddlab.rnd.testng.test.DummyTest.test2(DummyTest.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
      </class> <!-- com.ddlab.rnd.testng.test.DummyTest -->
    </test> <!-- case1 -->
  </suite> <!-- TestAll -->
</testng-results>
